added homework 2
DrozdovDenys/epam_angular_course pull request #2
Opened 2023-06-04 11:24 UTC by DrozdovDenys

2023-06-07 09:17 UTC, lemesh2424 requested changes

2023-06-07 09:17 UTC, lemesh2424 commented on src/app/components/main/main.component.html
Line 2: винеси змінну в парент компонент <app-search-bar [(searchInput)]="searchInput"></app-search-bar>
Line 9: *ngFor="let course of courses;" додай trackBy

2023-06-07 09:17 UTC, lemesh2424 commented on src/app/components/main/main.component.html
>  		[course]="course"
Додай output для кнопки Delete
Наприклад: (deleteClick)

2023-06-07 09:17 UTC, lemesh2424 commented on src/app/components/main/main.component.ts
> +export class MainComponent implements OnInit {
Додай будь ласка всі інші хуки

2023-06-07 09:17 UTC, lemesh2424 commented on src/app/app.module.ts
Створи будь ласка sharedModule та componentsModule в яких будуть окремо компоненти з кожної папки

2023-06-10 22:17 UTC, DrozdovDenys commented on src/app/components/main/main.component.html
виправив

2023-06-10 22:17 UTC, DrozdovDenys commented on src/app/components/main/main.component.ts
> +export class MainComponent implements OnInit {
додав

2023-06-10 22:18 UTC, DrozdovDenys commented on src/app/app.module.ts
створив

2023-06-10 22:20 UTC, DrozdovDenys commented on src/app/components/main/main.component.html
>  		[course]="course"
зробив для кнопки Edit

2023-06-24 13:14 UTC, merged